load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_image",
    "container_push"
)
load(
    "//adapters:docker.bzl", "image_descriptor"
)
load(
    "@rules_gitops//gitops:defs.bzl", "k8s_deploy"
)

CLUSTER = "kind-kind"

USER = "kind-kind"

REGISTRY = "localhost:15000"

platform(
    name = "linux_amd64",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
)

container_image(
    name = "image",
    base = "@alpine_linux_amd64//image",
    cmd = ["/bin/sleep", "10"],
    files = [":container_contents.txt"]
)

container_push(
    name = "push",
    image = "image",
    registry = REGISTRY,
    format = "Docker",
    repository = "rules_gitops/examples/legacy_docker/image"
)

image_descriptor(
    name = "k8s_image",
    image = "image",
    push = "push",
    registry = REGISTRY,
    repository = "rules_gitops/examples/legacy_docker/image"
)

k8s_deploy(
    name = "mynamespace",
    cluster = CLUSTER,
    images = [":k8s_image"],
    manifests = [
        "deployment.yaml",
    ],
    namespace = "{BUILD_USER}",
    user = USER,
)