load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["sidecar_client_test_no_callback.go"],
    importpath = "github.com/adobe/rules_gitops/testing/it_sidecar/client/test_no_callback",
    visibility = ["//visibility:public"],
    deps = ["//testing/it_sidecar/client:go_default_library"],
)
