load("//kustomize:defs.bzl", "KustomizeInfo")
load("//adapters:providers.bzl", "K8sPushInfo")

def _image_push_statements(
        ctx,
        kustomize_objs,
        files = []):
    statements = ""
    trans_img_pushes = depset(transitive = [obj[KustomizeInfo].image_pushes for obj in kustomize_objs]).to_list()
    statements += "\n".join([
        "echo  pushing {}/{}".format(exe[K8sPushInfo].registry, exe[K8sPushInfo].repository)
        for exe in trans_img_pushes
    ]) + "\n"
    statements += "\n".join([
        "async \"%s\"" % exe.files_to_run.executable.short_path
        for exe in trans_img_pushes
    ]) + "\nwaitpids\n"
    files += [obj.files_to_run.executable for obj in trans_img_pushes]
    dep_runfiles = [obj[DefaultInfo].default_runfiles for obj in trans_img_pushes]
    return statements, files, dep_runfiles

def _remove_prefix(s, prefix):
    return s[len(prefix):] if s.startswith(prefix) else s

def _remove_prefixes(s, prefixes):
    for prefix in prefixes:
        s = _remove_prefix(s, prefix)
    return s

def _gitops_impl(ctx):
    cluster = ctx.attr.cluster
    strip_prefixes = ctx.attr.strip_prefixes
    files = []

    push_statements, files, pushes_runfiles = _image_push_statements(ctx, ctx.attr.srcs, files)
    statements = """if [ "$PERFORM_PUSH" == "1" ]; then
{}
fi
    """.format(push_statements)

    namespace = ctx.attr.namespace
    for inattr in ctx.attr.srcs:
        if "{" in namespace:
            fail("unable to gitops namespace with placeholders %s" % inattr.label)  #mynamespace should not be gitopsed
        for infile in inattr.files.to_list():
            statements += ("echo $TARGET_DIR/{gitops_path}/{namespace}/{cluster}/{file}\n" +
                           "mkdir -p $TARGET_DIR/{gitops_path}/{namespace}/{cluster}\n" +
                           "echo '# GENERATED BY {rulename} -> {gitopsrulename}' > $TARGET_DIR/{gitops_path}/{namespace}/{cluster}/{file}\n" +
                           "{template_engine} --template={infile} --variable=NAMESPACE={namespace} --stamp_info_file={info_file} >> $TARGET_DIR/{gitops_path}/{namespace}/{cluster}/{file}\n").format(
                infile = infile.path,
                rulename = inattr.label,
                gitopsrulename = ctx.label,
                namespace = namespace,
                gitops_path = ctx.attr.gitops_path,
                cluster = cluster,
                file = _remove_prefixes(infile.path.split("/")[-1], strip_prefixes),
                template_engine = ctx.executable._template_engine.short_path,
                info_file = ctx.file._info_file.path,
            )

    ctx.actions.expand_template(
        template = ctx.file._template,
        substitutions = {
            "%{deployment_branch}": ctx.attr.deployment_branch,
            "%{statements}": statements,
        },
        output = ctx.outputs.executable,
    )
    runfiles = files + ctx.files.srcs + [ctx.executable._template_engine, ctx.file._info_file]
    transitive = depset(transitive = [obj.default_runfiles.files for obj in ctx.attr.srcs])

    rf = ctx.runfiles(files = runfiles, transitive_files = transitive)
    for dep_rf in pushes_runfiles:
        rf = rf.merge(dep_rf)
    return [
        DefaultInfo(runfiles = rf),
        KustomizeInfo(
            image_pushes = depset(transitive = [obj[KustomizeInfo].image_pushes for obj in ctx.attr.srcs]),
        ),
    ]

gitops = rule(
    attrs = {
        "srcs": attr.label_list(providers = (KustomizeInfo,)),
        "cluster": attr.string(mandatory = True),
        "namespace": attr.string(mandatory = True),
        "deployment_branch": attr.string(),
        "gitops_path": attr.string(),
        "release_branch_prefix": attr.string(),
        "strip_prefixes": attr.string_list(),
        "_info_file": attr.label(
            default = Label("//stamper:more_stable_status.txt"),
            allow_single_file = True,
        ),
        "_template_engine": attr.label(
            default = Label("//templating:fast_template_engine"),
            executable = True,
            cfg = "exec",
        ),
        "_template": attr.label(
            default = Label("//gitops/private:k8s_gitops.sh.tpl"),
            allow_single_file = True,
        ),
    },
    executable = True,
    implementation = _gitops_impl,
)