load("@bazel_lib//:bzl_library.bzl", "bzl_library")
load("@bazel_tools//tools/build_rules:test_rules.bzl", "rule_test")
load("//gitops:defs.bzl", "gitops")
load("//kubectl:defs.bzl", "kubectl_binary")
load("//kustomize:defs.bzl", "kustomization")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

# to generate new test data if needed:
# bazel run //skylib/kustomize:set_namespace newnamespace-1 <test.yaml >test_expected.yaml
sh_test(
    name = "set_namespace_test",
    size = "small",
    srcs = ["set_namespace_test.sh"],
    data = [
        "test.yaml",
        "test_expected.yaml",
        "//testing/private:set_namespace",
    ],
)

# Verify that rule is combining files without processing
kustomization(
    name = "raw_test",
    testonly = True,
    manifests = [
        "deployment.yaml",
        "service.yaml",
        "crb.yaml",
    ],
    namespace = "",
)

rule_test(
    name = "raw_generates_yaml",
    generates = ["raw_test.yaml"],
    rule = "raw_test",
)

# file_compare_test(
#     name = "raw_file",
#     expected = "goldens/expected_raw_test.yaml",
#     file = ":raw_test",
# )

kustomization(
    name = "namespace_test",
    testonly = True,
    manifests = [
        "deployment.yaml",
        "service.yaml",
        "crb.yaml",
    ],
    namespace = "bs-dev",
)

# file_compare_test(
#     name = "has_namespace",
#     expected = "goldens/expected_namespace_test",
#     file = ":namespace_test",
# )

filegroup(
    name = "alltestfiles",
    testonly = True,
    srcs = [
        "crb.yaml",
        "deployment.yaml",
        "service.yaml",
    ],
)

kustomization(
    name = "raw2_test",
    testonly = True,
    manifests = [
        ":alltestfiles",
    ],
    namespace = "",
)

# file_compare_test(
#     name = "raw2_file",
#     expected = "goldens/expected_raw_test.yaml",
#     file = ":raw2_test",
# )



kustomization(
    name = "image_test",
    testonly = True,
    images = [
        ":k8s_image",
    ],
    manifests = [
        "deployment.yaml",
        "service.yaml",
        "crb.yaml",
    ],
    namespace = "",
)

genrule(
    name = "goldens/expected_image_resolved_test_yaml",
    srcs = [
        ":goldens/expected_image_resolved_test.tpl.yaml",
        ":image.digest",
    ],
    outs = ["goldens/expected_image_resolved_test.yaml"],
    cmd = " ".join([
        "./$(location //templating:fast_template_engine)",
        "--template=$(location goldens/expected_image_resolved_test.tpl.yaml)",
        "--variable=IMAGE_DIGEST=$$(cat $(location :image.digest))",
        "--output=$@",
    ]),
    tools = [
        "//templating:fast_template_engine",
    ],
)

# file_compare_test(
#     name = "image_resolved_file",
#     expected = ":goldens/expected_image_resolved_test_yaml",
#     file = ":image_test",
# )

kustomization(
    name = "image_digest_test",
    testonly = True,
    images = [
        ":k8s_image",
    ],
    manifests = [
        "deployment.yaml",
        "service.yaml",
        "crb.yaml",
    ],
    namespace = "",
)

# file_compare_test(
#     name = "image_digest_resolved_file",
#     expected = "goldens/expected_image_resolved_test.yaml",
#     file = ":image_test",
# )

kustomization(
    name = "configmap_test",
    testonly = True,
    configmaps_srcs = glob(["configmaps/**/*"]),
    namespace = "",
)

# file_compare_test(
#     name = "configmap_test_file",
#     expected = "goldens/expected_configmap_test.yaml",
#     file = ":configmap_test",
# )

kustomization(
    name = "secret_test",
    testonly = True,
    namespace = "",
    secrets_srcs = glob(["secrets/**/*"]),
)

# file_compare_test(
#     name = "secret_test_file",
#     expected = "goldens/expected_secret_test.yaml",
#     file = ":secret_test",
# )

kustomization(
    name = "integration_test",
    testonly = True,
    images = [
        ":k8s_image",
    ],
    manifests = [
        "deployment.yaml",
        "service.yaml",
        ":configmap_test",
    ],
    namespace = "{BUILD_USER}",
)

kubectl_binary(
    name = "mynamespace.apply",
    testonly = True,
    srcs = [":integration_test"],
    cluster = "dev3",
    namespace = "test",
)

gitops(
    name = "dev-something.gitops",
    testonly = True,
    srcs = [":namespace_test"],
    cluster = "dev",
    namespace = "test",
)

#-------------------
kustomization(
    name = "name_prefix",
    manifests = ["test.yaml"],
    name_prefix = "prefix-",
    namespace = "",
)

# file_compare_test(
#     name = "name_prefix_test",
#     expected = "goldens/expected_name_prefix.yaml",
#     file = ":name_prefix",
# )

#-------------------
kustomization(
    name = "name_suffix",
    manifests = ["test.yaml"],
    name_suffix = "-suffix",
    namespace = "",
)

# file_compare_test(
#     name = "name_suffix_test",
#     expected = "goldens/expected_name_suffix.yaml",
#     file = ":name_suffix",
# )

#-------------------
# patch plus image
kustomization(
    name = "patch",
    images = [
        ":k8s_image",
    ],
    manifests = ["deployment.yaml"],
    namespace = "",
    patches = ["overlay/deployment.yaml"],
)

genrule(
    name = "goldens/expected_patch_yaml",
    srcs = [
        ":goldens/expected_patch.tpl.yaml",
        ":image.digest",
    ],
    outs = ["goldens/expected_patch.yaml"],
    cmd = " ".join([
        "./$(location //templating:fast_template_engine)",
        "--template=$(location goldens/expected_patch.tpl.yaml)",
        "--variable=IMAGE_DIGEST=$$(cat $(location :image.digest))",
        "--output=$@",
    ]),
    tools = [
        "//templating:fast_template_engine",
    ],
)

# file_compare_test(
#     name = "patch_test",
#     expected = ":goldens/expected_patch.yaml",
#     file = ":patch",
# )

#-------------------
# prefix and suffix for deployments: legacy compatibility
kustomization(
    name = "deployment_prefix_compat",
    manifests = ["deployment_with_labels.yaml"],
    name_prefix = "prefix-",
    namespace = "",
)

# file_compare_test(
#     name = "deployment_prefix_compat_test",
#     expected = "goldens/expected_deployment_prefix_compat.yaml",
#     file = ":deployment_prefix_compat",
# )

kustomization(
    name = "deployment_suffix_compat",
    manifests = ["deployment_with_labels.yaml"],
    name_suffix = "-suffix",
    namespace = "",
)

# file_compare_test(
#     name = "deployment_suffix_compat_test",
#     expected = "goldens/expected_deployment_suffix_compat.yaml",
#     file = ":deployment_suffix_compat",
# )

#-------------------
# prefix and suffix for deployments
kustomization(
    name = "deployment_prefix",
    configurations = ["//gitops:nameprefix_deployment_labels_config.yaml"],
    manifests = ["deployment_with_labels.yaml"],
    name_prefix = "prefix-",
    namespace = "",
)

# file_compare_test(
#     name = "deployment_prefix_test",
#     expected = "goldens/expected_deployment_prefix.yaml",
#     file = ":deployment_prefix",
# )

kustomization(
    name = "deployment_suffix",
    configurations = ["//gitops:namesuffix_deployment_labels_config.yaml"],
    manifests = ["deployment_with_labels.yaml"],
    name_suffix = "-suffix",
    namespace = "",
)

# file_compare_test(
#     name = "deployment_suffix_test",
#     expected = "goldens/expected_deployment_suffix.yaml",
#     file = ":deployment_suffix",
# )

#-------------------
# common labels and common annotations
kustomization(
    name = "common_labels",
    common_annotations = {"ownerTeam": "apps"},
    common_labels = {"flavor": "canary"},
    manifests = [
        "deployment_with_labels.yaml",
        "service.yaml",
    ],
    namespace = "",
)

# file_compare_test(
#     name = "common_labels_test",
#     expected = "goldens/expected_common_labels.yaml",
#     file = ":common_labels",
# )

#-------------------
# patch images

kustomization(
    name = "patch_images",
    image_name_patches = {
        "busybox": "alpine",
        "debian": "ubuntu",
    },
    image_tag_patches = {
        "busybox": "3",
    },
    manifests = [
        "job.yaml",
    ],
)

# file_compare_test(
#     name = "patch_images_test",
#     expected = "goldens/expected_job.yaml",
#     file = ":patch_images",
# )

