load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["sidecar_client.go"],
    importpath = "github.com/adobe/rules_gitops/testing/it_sidecar/client",
    visibility = ["//visibility:public"],
)
