load("@bazel_lib//:bzl_library.bzl", "bzl_library")

package(
    default_visibility = ["//kubectl:__subpackages__"],
)

bzl_library(
    name = "extension",
    srcs = ["extension.bzl"],
    deps = [
        ":platforms",
        "//kubectl/private/versions",
        "@bazel_tools//tools/build_defs/repo:cache.bzl",
        "@bazel_tools//tools/build_defs/repo:http.bzl",
        "@bazel_tools//tools/build_defs/repo:utils.bzl",
    ],
)

bzl_library(
    name = "toolchain",
    srcs = ["toolchain.bzl"],
    deps = [":providers"],
)

bzl_library(
    name = "kubectl_binary",
    srcs = ["kubectl_binary.bzl"],
)

bzl_library(
    name = "platforms",
    srcs = ["platforms.bzl"],
)

bzl_library(
    name = "providers",
    srcs = ["providers.bzl"],
)
