apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: //helloworld:image
          resources:
            requests:
              memory: 2Mi
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-object-name # <- secret object name without hash suffix
                  key: apikey
