load("//kustomize/private:kustomization.bzl", "kustomization")
load(":util.bzl", "golden_test")

# Verify that rule is combining files without processing
kustomization(
    name = "raw",
    testonly = True,
    manifests = [
        "deployment.yaml",
        "service.yaml",
        "crb.yaml",
    ],
    namespace = "",
)

golden_test(
    name = "raw_test",
    in_file = "raw"
)