load("@bazel_lib//:bzl_library.bzl", "bzl_library")
load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["update_versions.go"],
    importpath = "github.com/adobe/rules_gitops/kubectl/private/versions",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "update_versions",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "versions",
    srcs = ["versions.bzl"],
    visibility = ["//kubectl:__subpackages__"],
)
