"""Generated by update_versions.go - do not edit manually."""

LATEST_KUBECTL_VERSION = "1.35.0"

VERSIONS = {
    "1.35.0": {
        "darwin_amd64": "2447cb78911b10a667202b078eeb30541ec78d1280c3682921dc81607e148d96",
        "darwin_arm64": "cf699c56340dc775230fde4ef84237d27563ea6ef52164c7d078072b586c3918",
        "linux_amd64": "a2e984a18a0c063279d692533031c1eff93a262afcc0afdc517375432d060989",
        "linux_arm64": "58f82f9fe796c375c5c4b8439850b0f3f4d401a52434052f2df46035a8789e25",
    },
    "1.34.3": {
        "darwin_amd64": "657afbd0e653c4ce3af1b5a645a4eaba282cf8eb2bcda7191ff60866e50e4d7f",
        "darwin_arm64": "e51367d2107d605f4edd7c2fb25897b0c0695a7de1a9f9d04cd6c9356b890b14",
        "linux_amd64": "ab60ca5f0fd60c1eb81b52909e67060e3ba0bd27e55a8ac147cbc2172ff14212",
        "linux_arm64": "46913a7aa0327f6cc2e1cc2775d53c4a2af5e52f7fd8dacbfbfd098e757f19e9",
    },
    "1.33.7": {
        "darwin_amd64": "45be3f5293da84d97e86580a541b247fe3cec60196fdd6abd2b811d7dd4d3f1b",
        "darwin_arm64": "2e333f56d115081af83a48b5f31a91fb32852550f8117a0a31cf8bae2e601704",
        "linux_amd64": "471d94e208a89be62eb776700fc8206cbef11116a8de2dc06fc0086b0015375b",
        "linux_arm64": "fa7ee98fdb6fba92ae05b5e0cde0abd5972b2d9a4a084f7052a1fd0dce6bc1de",
    },
    "1.32.11": {
        "darwin_amd64": "8d0b610df71632d0e9b9c1aa16dde5ec666c05bf24e401ecf20fd27af16879ad",
        "darwin_arm64": "a39978a062f0df17d4a5551bd2e3a91eda90039196653935c50140be547141d3",
        "linux_amd64": "48581d0e808bd8b7d3c3fc014e86b170e25a987df04c8a879b982b28a5180815",
        "linux_arm64": "b1c91c106ec20e61c5dff869e9a39e6af4fb96572bddaac9cce307dfa3ed2348",
    },
    "1.31.14": {
        "darwin_amd64": "efcaa4da4ff8d1a4d08e972f24c06ab99de2f16bd91c436fd602a275b73d3b78",
        "darwin_arm64": "ee72e65cc206edc9b0d878e6d896fa31683dc1ba4c04944984efa07eebfc4725",
        "linux_amd64": "8791ec7c8966b61420d55103a5fb948de9f0ca3d7306d789734975ad9704bdb0",
        "linux_arm64": "3abb0c2d7121e1833831f56fd857a93de386e76d14b64baf86220d0afe495209",
    },
    "1.30.14": {
        "darwin_amd64": "9d9e5062fdba88b45f57d8fe322545d129cc5ef1e572f7f4f0c4b6579162b7da",
        "darwin_arm64": "af47a6a5f25630aa2bd68e56d21110b46aa1595a2d99f936637c75bc6bb65016",
        "linux_amd64": "7ccac981ece0098284d8961973295f5124d78eab7b89ba5023f35591baa16271",
        "linux_arm64": "a32e46ae15fe41292dc6a7cd76beba7104282a5a3fa9e3686319000a537f4f5d",
    },
    "1.29.15": {
        "darwin_amd64": "fe172c614d423b31d57dca699f1c3990042bfb90768512814d2614dce4563f15",
        "darwin_arm64": "1505a09992579bdc94565d872d840c97acfa84cc0478302491b58a754d4de5d6",
        "linux_amd64": "3473e14c7b024a6e5403c6401b273b3faff8e5b1fed022d633815eb3168e4516",
        "linux_arm64": "a41984dc0ff34ee05f1283ebd9b3121c003b3469b97214738246faa5b6788f7c",
    },
    "1.28.15": {
        "darwin_amd64": "3180c84131002037d60fe7322794c20297d0e1b1514eaea20e33f77a00d8f2f4",
        "darwin_arm64": "06a276bdb6da95af148d589f6c983ec8ea10c38f277ced6d97123938c8146078",
        "linux_amd64": "1f7651ad0b50ef4561aa82e77f3ad06599b5e6b0b2a5fb6c4f474d95a77e41c5",
        "linux_arm64": "7d45d9620e67095be41403ed80765fe47fcfbf4b4ed0bf0d1c8fe80345bda7d3",
    },
    "1.27.16": {
        "darwin_amd64": "8d7f339660ba9b33ed56d540bed41b37babc945975a9e7027010697249b9ac5a",
        "darwin_arm64": "d6bc47098bcb13a0ff5c267b30021b499aff4d960bd92610c2b0bc6f6e7246c9",
        "linux_amd64": "97ea7cd771d0c6e3332614668a40d2c5996f0053ff11b44b198ea84dba0818cb",
        "linux_arm64": "2f50cb29d73f696ffb57437d3e2c95b22c54f019de1dba19e2b834e0b4501eb9",
    },
    "1.26.15": {
        "darwin_amd64": "ad4e980f9c304840ec9227a78a998e132ea23f3ca1bc0df7718ed160341bad0b",
        "darwin_arm64": "c20b920d7e8e3ce3209c7c109fcfc4c09ad599613bc04b72c3f70d9fee598b68",
        "linux_amd64": "b75f359e6fad3cdbf05a0ee9d5872c43383683bb8527a9e078bb5b8a44350a41",
        "linux_arm64": "1396313f0f8e84ab1879757797992f1af043e1050283532e0fd8469902632216",
    },
    "1.25.16": {
        "darwin_amd64": "34e87fdf0613502edbd2a2b00de5ee8c7789ab10e33257d14423dc6879321920",
        "darwin_arm64": "d364f73df218b02642d06f3fa9b7345d64c03567b96ca21d361b487f48a33ccc",
        "linux_amd64": "5a9bc1d3ebfc7f6f812042d5f97b82730f2bdda47634b67bddf36ed23819ab17",
        "linux_arm64": "d6c23c80828092f028476743638a091f2f5e8141273d5228bf06c6671ef46924",
    },
    "1.24.17": {
        "darwin_amd64": "1eb904b2c1148ff8431b0bd86677287a48bff000f93fd2d36377fbe956bd1e49",
        "darwin_arm64": "7addbe3f1e22a366fa05aed4f268e77e83d902b40a5854e192b4205ed92e5f8d",
        "linux_amd64": "3e9588e3326c7110a163103fc3ea101bb0e85f4d6fd228cf928fa9a2a20594d5",
        "linux_arm64": "66885bda3a202546778c77f0b66dcf7f576b5a49ff9456acf61329da784a602d",
    },
    "1.23.17": {
        "darwin_amd64": "7ece6543e3ca2ae9698ef61bbb2a4e249aa21319df4ea1b27c136a9b005dd7d8",
        "darwin_arm64": "3b4590d67b31e3a94a9633064571c981907555da5376c34960cddfcd552f6114",
        "linux_amd64": "f09f7338b5a677f17a9443796c648d2b80feaec9d6a094ab79a77c8a01fde941",
        "linux_arm64": "c4a48fdc6038beacbc5de3e4cf6c23639b643e76656aabe2b7798d3898ec7f05",
    },
    "1.22.17": {
        "darwin_amd64": "c3b8ae5ad48e1e126b5db2e7e22bb1e6ac54901a7f94ce499d12316f705e5e15",
        "darwin_arm64": "b2d881bd6d3c688645cbc9e5b4cf4fe8945e1cfc3f2c07c795d2ee605ce4e568",
        "linux_amd64": "7506a0ae7a59b35089853e1da2b0b9ac0258c5309ea3d165c3412904a9051d48",
        "linux_arm64": "8fc2f8d5c80a6bf60be06f8cf28679a05ce565ce0bc81e70aaac38e0f7da6259",
    },
    "1.21.14": {
        "darwin_amd64": "30c529fe2891eb93dda99597b5c84cb10d2318bb92ae89e1e6189b3ae5fb6296",
        "darwin_arm64": "e0e6e413e19abc9deb15f9bd3c72f73ff5539973758e64ebca0f5eb085de6a00",
        "linux_amd64": "0c1682493c2abd7bc5fe4ddcdb0b6e5d417aa7e067994ffeca964163a988c6ee",
        "linux_arm64": "a23151bca5d918e9238546e7af416422b51cda597a22abaae5ca50369abfbbaa",
    },
    "1.20.15": {
        "darwin_amd64": "6b6cf555a34271379b45013dfa9b580329314254aafc91b543bf2d83ebd1db74",
        "linux_amd64": "d283552d3ef3b0fd47c08953414e1e73897a1b3f88c8a520bb2e7de4e37e96f3",
        "linux_arm64": "d479febfb2e967bd86240b5c0b841e40e39e1ef610afd6f224281a23318c13dc",
    },
}
