load("@bazel_lib//:bzl_library.bzl", "bzl_library")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "defs",
    srcs = ["defs.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        "//kubectl/private:extension",
        "//kubectl/private:kubectl_binary",
        "//kubectl/private:toolchain",
    ],
)
