"""Generated by update_versions.go - do not edit manually."""

LATEST_KUSTOMIZE_VERSION = "5.8.0"

VERSIONS = {
    "5.8.0": {
        "darwin_amd64": "2deaa6f96450c0b3204cccd9f159a22278eb6cf85ad545d212d608d2428aeb57",
        "darwin_arm64": "d098f62ecda500c752303163838af823f947d245927f3000b629199c1eeeae0f",
        "linux_amd64": "4dfa8307358dd9284aa4d2b1d5596766a65b93433e8fa3f9f74498941f01c5ef",
        "linux_arm64": "a4f48b4c3d4ca97d748943e19169de85a2e86e80bcc09558603e2aa66fb15ce1",
        "linux_ppc64le": "4352a29912b6a15688598ec192e79b841ee8b128ba411592d1de68b585009ec7",
        "linux_s390x": "f7be07697c1ba872ff4e99806ac9a86faa7029e108a24ccfa7b47c04c1cc9c0d",
    },
    "5.7.1": {
        "darwin_amd64": "4a0dff80c5644df6bc8f51b342842969004cb6ba5f94dddaabbea7483493273d",
        "darwin_arm64": "073e9d16d5a235e2ff83e62d6b76edb5d962adbc33be1e4860c4b3f1f39b33b9",
        "linux_amd64": "ea375e7372f9aa029129d4b2d16c66b7750b7f1213c4f66f910d981c895818d8",
        "linux_arm64": "4261a040217df3bd6896597c3986d1465925726e4f22a945304b5233a4dcdbda",
        "linux_ppc64le": "56b6fbf549080b14ddc738f10a05f78cbc5511cd7ab2014d9eb85f52bb4b7263",
        "linux_s390x": "b1eee427af74f3bb53d96e3ba94d5cc7484a35bb1af1495488bc684d60df4488",
    },
    "5.7.0": {
        "darwin_amd64": "277a7401f969ce3945e8f0ff8b0cce6f4353854db1ff89ba070001e3246e7f22",
        "darwin_arm64": "c0dac68dc7870e1f673ae4d8fb554df971e0b9b9f0affc4be4c0852f62d0796e",
        "linux_amd64": "0d98f06d6d2c2c0ff8923cc136a517af74aaa187f1b9f3e17ff370d0625ede84",
        "linux_arm64": "744bb1bc1854b6634dea9eaf6db2f401a734ed25d6837baa6f91157d79c27d5e",
        "linux_ppc64le": "752e750d5f349156ea228ae01cf57be22e6cc29f0f05748a1bca7fa870393561",
        "linux_s390x": "64898beb154a111c1a98f8cff066fdfa866c4c73505e9a9b5fa6ec39f0292558",
    },
}
