load("@bazel_lib//:bzl_library.bzl", "bzl_library")

package(
    default_visibility = ["//kustomize:__subpackages__"],
)

bzl_library(
    name = "extension",
    srcs = ["extension.bzl"],
    deps = [
        ":platforms",
        "//kustomize/private/versions",
        "@bazel_tools//tools/build_defs/repo:cache.bzl",
        "@bazel_tools//tools/build_defs/repo:http.bzl",
        "@bazel_tools//tools/build_defs/repo:utils.bzl",
    ],
)

bzl_library(
    name = "kustomization",
    srcs = ["kustomization.bzl"],
    deps = [
        ":providers",
        "//adapters:providers",
        "//stamper:stamp",
    ],
)

bzl_library(
    name = "toolchain",
    srcs = ["toolchain.bzl"],
    deps = [":providers"],
)

bzl_library(
    name = "kustomize_binary",
    srcs = ["kustomize_binary.bzl"],
)

bzl_library(
    name = "platforms",
    srcs = ["platforms.bzl"],
)

bzl_library(
    name = "providers",
    srcs = ["providers.bzl"],
)

bzl_library(
    name = "resolved_toolchain",
    srcs = ["resolved_toolchain.bzl"],
)

bzl_library(
    name = "show",
    srcs = ["show.bzl"],
)
