name: CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        bazel-version:
          - 7.6.0
          - 8.5.0
          - 9.0.0
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Mount Bazel cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: bazel-${{ matrix.bazel-version }}-${{ github.sha }}
          restore-keys: |
            bazel-${{ matrix.bazel-version }}-
            bazel-
      - name: Setup build tools
        run: |
          TOOLS_DIR="${HOME}/.cache/tools"
          mkdir -p "${TOOLS_DIR}/bin/"
          curl -Ls -o "${TOOLS_DIR}/bin/bazel" "https://github.com/bazelbuild/bazelisk/releases/download/v1.14.0/bazelisk-linux-amd64"
          chmod +x "${TOOLS_DIR}/bin/bazel"
          echo "${TOOLS_DIR}/bin" >> $GITHUB_PATH
      - name: Test
        run: |
          bazel test //... --config=ci
      - name: Build helloworld
        run: |
          cd examples/helloworld
          bazel build //... --config=ci
      - name: Build legacy docker
        if: matrix.bazel-version == '7.6.0'
        run: |
          cd ../legacy_docker
          bazel build //... --config=ci
